#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UiAction {
    None,
    Quit,
    StartSession,
    NewSession,
    NextStep,
    PrevStep,
    JumpRecommended,
    JumpBack,
    Verify,
    Hint,
    Suggest(Option<usize>),
    ClearLog,
    ShowHelp,
    ShowShellMode,
    SetShellMode(String),
    DismissPopup,
    RunCommand(String),
    ForceRunCommand(String),
    SetCommandInput(String),
    SetPanelIndex { index: usize },
    NextPanelIndex,
    PreviousPanelIndex,
}
